const entry = [
    "Today I saw a new sunflower patch in the middle of the sidewalk on Hampshire. I have no idea how it appeared overnight.",
    "I read a poem every day. Every poem this week has left me in tears.",
    "M is coming over to work today but I really just want to watch the new episode that just came out.",
    "I’ve been calling N every evening and I don’t tell her enough, but I love the company. It makes all the difference.",
    "Today I shall forgive myself for my unformed opinions.",
    "I’m struggling to find the words to express in this letter - poetry might be the only form that will feel right.",
    "The most powerful thing I can do is cultivate a good gut.",
    "My preferred way of flirting is saying I think you and I could make beautiful zines together.",
    "I wish to be love abundant.",
    "Foliage forecaster is a job.",
    "Art from suffering is not better, but I suppose I am glad to have this place to hold my most painful self.",
    "A Friday night crafting while watching the newest episode of bakeoff is a small pocket of the purest joy.",
    "I think I met one of my parts today - a younger me, wanting to stay true to her feelings and scared of not being able to trust herself.",
    "I listened to my joy (pink storage cubes).",
    "To visit a place year after year and meet the snapshots of all of your past selves - they have so many questions to ask me.",
    "Just read an article that said if you have to swallow a frog today, do it first thing. If you have two, swallow the biggest frog first, and I love that phrasing. What is my frog rn?",
    "I think I have five big frogs right now.",
    "The internet has weather too.",
    "What would it be like to nurture a project over time without deadline, without decay in excitement that leads to dread? To work on my own secret thing away from external pressures? To come home to it everyday knowing I’d never have to rush.",
    "The visi-sonor is one of the first items described in sci-fi that make me go… this feels good.",
    "If I spend a year like this, imagine where I'll be next year.",
    "I downloaded a book on dandelions on a whim. I didn’t have the time to read it but I did.",
    "I feel an excitement so forceful it knocks me out of focus (this happens too often, be still my heart)",
    "Shadows are really orienting? Sunny days are great bc shadows offer contrast -- cloudy/gray days feel off due to the sameness of hue everywhere.",
    "I’m feeling so lucky and full of love, I am filled to the brim and overflowing.",
    "How would I act if I really cared about the things I said I did!",
    "To say I am present here with you is to say I love you.",
    "I LOVE a good unreliable narrator // I’m starting to feel a bit unreliable myself.",
    "Is this thought causing me to suffer? could i stop listening to it... and not suffer?",
    "I want to become intimate with a color.",
    "I'm getting into romcoms again. Maybe this is what they mean by nature is healing. To wish to be a girl in a string of coincidences that lead to the perfect guy.",
    "Speaking is a position of power. I admire people who naturally take up space and make space for others.",
    "Thinking about the ways dependence can lead to independence, how we can fearlessly fail when we have a support system to come back to.",
    "How much my life would improve if I didn't get so car sick. What other bits of my life would have this much impact?",
    "One intention I set for these next few months was to spend less time on food, because as much as I love to cook and plan where I'll have my next meal, it takes so much time and mental space.",
    "While the cheesecakes were baking N convinced me to start a new book and I did a warm eye compress. At some point when I was cleaning up my roommate walked in and asked if I was okay, it seemed like I had been in the kitchen for six hours. just a casual thursday night.",
    "I’m convinced this keylime cheesecake can make any man fall in love with me. Any woman too.",
    "Grief always catches up to me in this last week of the year, for the versions of myself that I feel I did not stay true to and for the love I've let dwindle. And yet there is still so much joy.",
    "Every time we bring back a dog we think what have gotten ourselves into, how have we committed three weeks to a dog that seems so distant from us and has already peed inside. I know I will love her so much.",
    "I'm spending the holidays with my parents in Texas where it's warm and sunny and I still call it home. I wonder when I'll stop saying 'I'm going home.'",
    "It rained today. As in, looked like enough rain to warrant an umbrella, yet when I opened mine the drops made no sound. It felt a bit silly to carry an umbrella for raindrops that leave no mark.",
    "There are a few things I do daily now. I paint a small square of the sky each day. I read a poem each day. I feel impure when I put them on the todo list, after all, rituals shouldn't need checkboxes, no?",
    "In this discomfort I realize that I have a sense of home, small as it is. When the grayness-but-really-white-lack-of-shadows gets to me I wishi to be in my room, where the warm glow of half a dozen bulbs and my craft table feel like a hug.",
    "N did my tarot reading while I cooked and said I had no cup cards. I’m not driven by emotion right now. I should take a break or risk burnout, there is an abundance of creativity right now, I shouldn't stay in a job I dislike, and there will soon be a work/relationship situation where I'll have to stand my ground with my values.",
    "It’s raining and I’m sitting on a tram and getting a peak into everyone’s gardens as I pass by. I imagine these are the perfect balance of privacy and connection that Alexander mentions.",
    "There’s something about rain that is an equalizer, like the night. Trudging through rainwater in one city is pretty close to trudging through rainwater in any other city.",
    "Got that vegan burger for lunch, slept, and got the potato gift.",
    "Eavesdropped on the conversation in the kitchen.",
    "Made dinner, annotated all 1000 sentences, and met with B. She is more lost than me I think.",
    "Had my therapy session and of course I cried. But I only cry during these sessions.",
    "B called to ask about salary and then started crying so we talked for an hour about job options and boys and the dynamics here.",
    "Still got up around noon. Today was a decent day. The meeting got moved and passed out after dinner.",
    "Did abs with J then got distracted during lecture learning about cells from an anime.",
    "Interview and the person didn’t smile I have no idea what to do with the ones who don’t smile.",
    "Meetings meetings meetings and then pasta making with Pietro. I miss Italy.",
    "Drew a portrait in blue bc I felt blue and it was pretty helpful.",
    "J was back today. I smiled and said hi in passing and then felt so relieved.",
    "Walked from the library to the old office and then stopped in Walgreens to get lashes while waiting for N and E.",
    "We walked from the bookstore and ate our food at the park. We lay down on the blanket and talked. Whose memoirs would I read?",
    "I think about how much I love A. It scares me because this is the first moment that it hits like this could really really hurt me.",
    "I got emotional in the bookstore picking things out and putting them on hold.",
    "Cava for din and tried watching half a horror movie with N. Started Hereditary when they got back why are we always watching horror movies.",
    "I’m an emotionless brick sometimes.",
    "Apparently I am not yet great at getting up early. That is ok.",
    "Watched bachelorette with them while doing ethics homework and texting Y. I like that we’ve texted a lot today.",
    "Bike was ok. It was nice to be w a group though I realized that when I walk I prefer to stay silent and enjoy myself.",
    "I think I have a better grasp of what I’m doing but I still feel like I'm behind.",
    "Had a work social which was pretty fun. I wanted to play codenames but we played drawing games instead. I always think they won’t be fun but then I get really into them and competitive.",
    "My intentions for the day are to get a good deal of work done I suppose!",
    "And I keep writing and writing and writing for a whole three minutes maybe? Is that three pages? If I do this continuously, will my creative energy be unblocked?",
    "Funny how with any journaling, I always come out with actionables. Things I can do and if nothing else that is a reason to keep writing. I have so many loves that have been subdued.",
    "How do you know if you love somebody?",
    "I want to write poems instead of just reading, I want to do research instead of just consuming. I want to create art instead of just being jealous.",
    "I feel super overwhelmed and worried that I won't be able to be present when I'm with G because I'll be thinking so much about work.",
    "How has half a year passed by so quickly here? How did I end up in a place where time passes by so quickly? I want slowness where every day is full.",
    "I don't particularly have much to say today other than it's nice to be home and I am feeling myself pull in parts of adult me that have been dormant for a while.",
    "It feels weird not to be surrounded by people anymore. I will definitely miss that.",
    "I feel very STUCK. I don't know what to do right now and there's no way forward. I'm literally just frozen in time unable to do anything. I wonder why. My body feels physically tired.",
    "The transition of seasons is really getting to me and I'm lost in time. I don't know what summer it is anymore.",
    "I think spending some time with me will be good today.",
    "I keep going and going and going. Once I get a chocolate in me I will be unstoppable.",
    "What would be the fun thing?? Writing a substack? Also a lot of things to submit!!",
    "Summer in boston is magical. I've never seen things SO GREEN and the water so sparkly and I wouldn't be surprised if there were fairies all around us. I've been a bit in my own head this past week and forgotten to notice how the city was glowing around me. I forgot to breathe.",
    "Today I am not yet quite at love.",
    "I feel really seen when I’m around E.",
    "I am a fucking powerful witch.",
    "I feel that fluttery feeling in my stomach. I think I am nervous. I'm toeing the threshold, where I truly am my own person.",
    "We skipped a whole summer here. I walked back the way from work - about an hour but more because I think I took a longer way. I decided to walk because I don’t like the way the trains feel except for when they’re completely empty but G called and I felt so bothered that I decided to walk it off and ended up crying it out too.",
    "There's something about walking through a city crying at night. therapeutic? Revealing?",
    "In the dark, it is safe to feel everything where only the moon and the glowing dandelions can see you.",
    "I feel my attention being scrambled all the time. How did I get myself into three hobby classes and all of these projects and work and needing to find friends and the weight of maintaining and maintaining and maintaining.",
    "Received a letter from A today and I felt my heart burst. I feel so warm but now the pressure to send a letter back soon is even greater. This feels so much better than texting.",
    "Called mom today to ask about the meatball recipe. Every time I cook I want to make something new but I don’t have time for this.",
    "I must finish my readings. Then I must write my essay, then do my laundry, then call A, then make my returns, then go to pottery. That’s only like 5 things.",
    "Started this book to appease N but now it is 5am and I cannot put this down. I cannot leave until she is back with the impossibly perfect guy.",
    "I’m finally writing poetry again and I feel at home.",
    "I predict great difficulty in creating community in the absence of finding one waiting but I know it can be done.",
    "What if the truth is.. that I won’t have time to sleep with all that I want to do.",
    "I’m feeling great! The sun has graced us all week and I think that I could have a life here.",
    "I want SOUP. What soups are in my arsenal.",
    "My craving leads me to burrito.",
    "I dreamt of poetic phrases that have since faded. If I nap again will they come back?",
    "The sky feels like a Barbie movie.",
    "I dance every night in my room and put on flashing lights. It’s a nightclub for one and may be the secret to life.",
    "I’ve been craving cream puffs since Thanksgiving.",
    "This was a good week for the sky.",
    "I want to make a chair.",
    "I want to sew a dress.",
    "I want to make spaghetti.",
    "I should buy some flowers.",
    "I want some cheese.",
    "So glad L was also at the party, we get to have our little introvert corner together.",
    "Just found out that both ice cream places have new flavors every month."
];



// const sentenceLengths = {};

// for (const ent of entry) {
//     const length = ent.length;
//     if (sentenceLengths[length]) {
//         sentenceLengths[length].push(ent)
//     } else {
//         sentenceLengths[length] = [ent];
//     }
// }

// console.log(sentenceLengths)