const entry = 
  [
    "I want a hug..",
    "What if we...?",
    "I want a kiss.",
    "I want cheese.",
    "I miss A today.",
    "I miss Y a lot.",
    "It's been a while since I've called D.",
    "I want to sew a dress.",
    "Going to call N today.",
    "Maybe I'll finish that book.",
    "I want to make a chair.",
    "Our joys have diverged.",
    "What if I wrote a book?",
    "I want to make spaghetti.",
    "I always love beginnings.",
    "I should buy some flowers.",
    "Today will be a great day.",
    "I wish to be love abundant.",
    "Slept at 4am, woke up 10am.",
    "Foliage forecaster is a job.",
    "Same behavior, same outcome.",
    "I'm an artist. Never forget.",
    "What if I wrote a manifesto?",
    "Did you know the internet has weather too.",
    "I am a freaking powerful witch.",
    "My craving leads me to burrito.",
    "Back on the artist's way grind.",
    "Today I am not yet quite at love.",
    "This was a good week for the sky.",
    "I had such grand plans yesterday!",
    "The sky feels like a Barbie movie.",
    "I too, can weaponize incompetence.",
    "I'm an emotionless brick sometimes.",
    "Does journaling take too much time?",
    "How do you know if you love somebody?",
    "I feel really seen when I'm around E.",
    "Lovely day in store from here on out.",
    "There's so many wonderful communities.",
    "Overwhelmed!!! I feel so Overwhelmed!!",
    "I want to become intimate with a color.",
    "There's so much that I wish to learn!!!",
    "I think I have five big frogs right now.",
    "Maintenance: remember to update website.",
    "This amount of writing is for my sanity.",
    "A dance a day keeps the depression away.",
    "Unfinished project reminder: tarot rooms.",
    "I was blessed with good nap dreams today.",
    "I listened to my joy (pink storage cubes).",
    "I want SOUP. What soups are in my arsenal.",
    "This is the feeling of empty, of yearning.",
    "I have an abundance of feelings right now.",
    "My biggest frog today is just reading this paper.",
    "Today, I must apply for the scholarship. MUST!!",
    "Affirmation: I bless others with my creativity.",
    "My energy levels are low… but sleep is so good!",
    "Eavesdropped on the conversation in the kitchen.",
    "If agency is reduced by burnout then where am I?",
    "I've been craving cream puffs since Thanksgiving.",
    "Unfinished project reminder: shrub club syllabus.",
    "I've missed important deadlines for the last time now.",
    "I had a beautiful dream for what we could be.",
    "I'm finally writing poetry again and I feel at home :').",
    "My pocket has half an ibuprofen and a vitamin d pill.",
    "Every symptom of mine can be attributed to womanhood.",
    "Today I shall forgive myself for my unformed opinions.",
    "I think spending some time with me will be good today.",
    "I'm not as swamped as I initially imagined I would be.",
    "Working through the 12 steps of TV addiction recovery.",
    "To say I am present here with you is to say I love you.",
    "I want to be able to cheer Y up when he's feeling down.",
    "What if I could turn this sensation into something else?",
    "The most powerful thing I can do is cultivate a good gut.",
    "I have to work in working places. No more working in bed.",
    "I can't really consume media anymore. It just won't go in my brain anymore.",
    "If I spend a year like this, imagine where I'll be next year.",
    "I'm working on my audacity today. I will cancel this meeting.",
    "Apparently I am not yet great at getting up early. That is ok.",
    "I think this time I get to be brutally honest w/ my therapist.",
    "I may never be caught up again in my life. I think that's okay.",
    "I'm trying to reach out in small ways for the first time today.",
    "How would I act if I really cared about the things I said I did!",
    "Got that vegan burger for lunch, slept, and got the potato gift.",
    "M texted me about my daily paintings and my heart feels so warm.",
    "Drew a portrait in blue bc I felt blue and it was pretty helpful.",
    "Days are so short on a calendar but the days themselves are full!",
    "I read a poem every day. Every poem this week has left me in tears.",
    "I have about a million things to do! What a wonderful life of mine.",
    "It was so easy to stay up last night.. felt like I was in a trance?",
    "When will I be able to email without the considerations of girlhood?",
    "When the world is a canvas, you never run out of new mediums to try.",
    "Today I still feel overwhelmed - but I feel better equipped to handle it.",
    "My intentions for the day are to get a good deal of work done, I suppose!",
    "The important thing is that I'm writing, regardless of where it is right?",
    "I have seven hours of pottery scheduled today and I think I may be insane.",
    "I never heard back from that one submission. I wonder if they got my poem.",
    "N calls me every night before she sleeps and then I call A before I sleep.",
    "Meetings meetings meetings and then pasta making with Pietro. I miss Italy.",
    "J was back today. I smiled and said hi in passing and then felt so relieved.",
    "I feel comfortable in this space. I don't know how to do work in this space.",
    "I got emotional in the bookstore picking things out and putting them on hold.",
    "I love my mom and dad. I love A. I love pink. I don't love being on a budget.",
    "I'm feeling so lucky and full of love -- I am filled to the brim and overflowing.",
    "I think I have a better grasp of what I'm doing but I still feel like I'm behind.",
    "I LOVE a good unreliable narrator // I'm starting to feel a bit unreliable myself.",
    "What would be the fun thing?? Writing a substack? Also a lot of things to submit!!",
    "What if the truth is.. that I won't have time to sleep with all that I want to do.",
    "How many hours am I actually working each day? I spent 7 hrs on pottery yesterday…",
    "Had my therapy session and of course I cried. But I only cry during these sessions.",
    "It feels weird not to be surrounded by people anymore. I will definitely miss that.",
    "Is this thought causing me to suffer? could i stop listening to it... and not suffer?",
    "Did abs with J then got distracted during lecture learning about cells from an anime.",
    "I keep going and going and going. Once I get a chocolate in me I will be unstoppable.",
    "I dreamt of poetic phrases that have since faded. If I nap again will they come back?",
    "So glad L was also at the party, we get to have our little introvert corner together.",
    "Went to the grocery store to get a singular orange. Cooked fried rice with leftovers.",
    "I feel UNFORMED! so soft and malleable. I could be pressed in so many directions now.",
    "Dreams: forgot the details but again I was trying to survive in an apocalyptic world.",
    "There's something about walking through a city crying at night. therapeutic? Revealing?",
    "I'm used to thinking in chunks of one (1) day at a time. I'll map out a timeline maybe.",
    "I dream of writing a poem that reaches G's soul - one that needs no explaining from me.",
    "I have a lot of love for these girls. I want to respond to them. I want to stop using I so much.",
    "I downloaded a book on dandelions on a whim. I didn't have the time to read it but I did.",
    "I feel the kettle to see if it's warm and know whether my roommate made tea this morning.",
    "I'm convinced that this keylime cheesecake can make any man fall in love with me. Any woman too.",
    "Made dinner, annotated all 1000 sentences, and met with B. She is more lost than me I think.",
    "I'm feeling great! The sun has graced us all week and I think that I could have a life here.",
    "I'm also unhappy with how work has been going. It feels like I'm not doing enough of either.",
    "My preferred way of flirting is saying \"I think you and I could make beautiful zines together.\"",
    "The visi-sonor is one of the first items described in sci-fi that make me go… this feels good.",
    "Interview and the person didn't smile I have no idea what to do with the ones who don't smile.",
    "I'm choosing to say no to these two applications. Am I too burnt out or am I just intimidated?",
    "I think I'll make a print tonight. Or a plot thing. Or a sketch. Or start the book. Or my poem.",
    "I worry about all of my engagements.. but one thing is .. I'm more earnest that I've ever been.",
    "Today I met a guy who knows J and A. It's such a small world but sometimes I wish it were even smaller.",
    "M is coming over to work today but I really just want to watch the new episode that just came out.",
    "And here I was sitting on the ground stuck w/ my love of thinking. Really sitting w/ the feelings.",
    "It's 3:30pm and I'm starting my day - watching a whole season last night was not the smartest move.",
    "I think A changed the way that I think. Anyone with that amount of love has to leave an impression.",
    "Still got up around noon. Today was a decent day. The meeting got moved and passed out after dinner.",
    "Two nights this week I crawled out of bed right as I was about to fall asleep to write down an idea.",
    "If I follow my jealousy and it takes me down three different fields and 30 mediums, can it be trusted?",
    "I feel an excitement so forceful it knocks me out of focus (this happens too often, be still my heart)",
    "In the dark, it is safe to feel everything where only the moon and the glowing dandelions can see you.",
    "Speaking is a position of power. I admire people who naturally take up space and make space for others.",
    "It's hard to do things. I cook every day. I go to school, I cook, I watch a little TV and that's my day and then it's over?",
    "A Friday night crafting while watching the newest episode of bakeoff is a small pocket of the purest joy.",
    "I don't feel like I belong here but that's a good thing. I want to be the odd one out but still loveable.",
    "Art created from suffering is not better, but I suppose I am glad to have this place to hold my most painful self.",
    "But when I was napping in my blankets slightly in the sun, I felt like a cat and that's what life must be about.",
    "Watched bachelorette with them while doing ethics homework and texting Y. I like that we've texted a lot today.",
    "The transition of seasons is really getting to me and I'm lost in time. I don't know what summer it is anymore.",
    "I'm struggling to find the words to express in this letter - poetry might be the only form that will feel right.",
    "Walked from the library to the old office and then stopped in Walgreens to get lashes while waiting for N and E.",
    "It's a beautiful day. I should take advantage of it. The rain hasn't bothered my mood, just physical discomfort.",
    "I predict great difficulty for creating community in the absence of finding one waiting but I know it can be done.",
    "I dance every night in my room and put on flashing lights. It's a nightclub for one and may be the secret to life.",
    "I feel better about housing now. All it took was knowing that I had tried hard and had a grasp on all the options.",
    "I've been calling N every evening and I don't tell her enough, but I love the company. It makes all the difference.",
    "How much my life would improve if I didn't get so car sick. What other bits of my life would have this much impact?",
    "I was so scared of not being able to keep up a practice that I over committed myself in the name of accountability.",
    "I breathe into my mug and let the steam warm up my nose with toasted rice scent that is better than the tea itself.",
    "Bike was ok. It was nice to be w a group though I realized that when I walk I prefer to stay silent and enjoy myself.",
    "Today the main thing is still this study but maybe I can't do anything until I clean and get tomorrow's things ready.",
    "Today I saw a new sunflower patch in the middle of the sidewalk. I have no idea how it appeared overnight. It's HUGE!",
    "It's really easy to separate the ppl who take care of themselves and the ppl who don't just by whether they drink water.",
    "To visit a place year after year and meet the snapshots of all of your past selves - they have so many questions to ask me.",
    "I feel that fluttery feeling in my stomach. I think I am nervous. I'm toeing the threshold, where I truly am my own person.",
    "We walked from the bookstore and ate our food at the park. We lay down on the blanket and talked. Whose memoirs would I read?",
    "I can't believe I'm eating prepackaged meals. I can't believe how helpful they are when I'm busy. Has it really come to this?",
    "B called to ask about salary and then started crying so we talked for an hour about job options and boys.",
    "Called mom today to ask about the meatball recipe. Every time I cook I want to make something new but I don't have time.",
    "I think about how much I love A. It scares me because this is the first moment that it hits - like this could really really hurt me.",
    "I feel super overwhelmed and worried that I won't be able to be present when I'm with G because I'll be thinking so much about work.",
    "Somedays this IUD feels like an alien object implanted in me. I feel deeply uncomfortable with what is out of my control in my body.",
    "A straight back is the sign of alignment. Where does the energy flow within me? Why do I always feel like I'm forgetting to breathe?",
    "Thinking about the ways dependence can lead to independence, how we can fearlessly fail when we have a support system to come back to.",
    "The clouds in Texas make the sky look infinite, but the clouds here have a way of making the sky look magnificent. Can a sky be grand?",
    "I desperately want to be able to write and converse with my friends and learn more and participate and do my silly little experiments.",
    "I think I met one of my parts today - a younger me, wanting to stay true to her feelings and scared of not being able to trust herself.",
    "So many things I haven't had enough practice at. Most things can realistically be remedied. But who has enough practice at breaking up?",
    "I woke up today thinking I'm lonely. It's not a feeling, just a fact, and not one that bothers me. This feels like the life of my parents.",
    "I'm so very happy but also so very overwhelmed and it doesn't help that Rebecca may be the best book I've read all year and now it's over.",
    "Cava for din and tried watching half a horror movie with N. Started Hereditary when they got back why are we always watching horror movies.",
    "I have so much running inside right now that even journaling feels like a daunting task, but I rest easy knowing that I have limited pages.",
    "Started this book to appease N but now it is 5 am and I cannot put this down. I cannot leave until she is back with the impossibly perfect guy. Why must imagination be so cruel!",
    "Shadows are really orienting? Sunny days are great bc shadows offer contrast - cloudy / gray days feel off due to the sameness of hue everywhere.",
    "I feel like I'm in a good place despite other things : ) the creative energy is coming back through reading - I might have a mild concussion hmm.",
    "I want to be writing poems instead of just reading, I want to do research instead of just consuming. I want to create art instead of just being jealous.",
    "How has half a year passed by so quickly here? How did I end up in a place where time passes by so quickly?? I want a slowness where every day is full -",
    "I'm spending the holidays with my parents in Texas where it's warm and sunny and I still call it home. I wonder when I'll stop saying: \"I'm going home.\"",
    "I must finish my readings. Then I must write my essay, then do my laundry, then call A, then make my returns, then go to pottery. That's only like 5 things right?",
    "I'm getting into romcoms again. Maybe this is what they mean by nature is healing. To wish to be a girl in a string of coincidences that lead to the perfect guy.",
    "And I keep writing and writing and writing for a whole three minutes maybe? Is that three pages? If I do this continuously, will my creative energy be unblocked?",
    "I don't particularly have much to say today other than it's nice to be home and I am feeling myself pull in parts of adult me that have been dormant for a while.",
    "Today I called my mom and asked her what she puts in her dumpling fillings.I call her for more things that I need these days and it makes me feel so much closer.",
    "I forgot to buy toothpaste again. Also need to remember to grab an onion, some garlic, and a tomato. I should stay strong and not cave for the soft sugar cookies.",
    "I woke up feeling thirsty, with another brick in my stomach. This one's a little softer, a little more compressible. I look at my phone and am hit with… jealousy?",
    "I just watched an hour long video of someone talking about time management and it feels like so much of being able to have more time is having the audacity of a man.",
    "I'm avoiding thinking about my research b/c it seems like such an impossibly large task that I'm not qualified for, but also? it takes TIME idk why that feels wrong.",
    "I've painted my sky today. I still need to do my poem, workout, brush my teeth, drink water, respond to A, respond to L, respond to J, try to catch up in the Discord, respond to emails.",
    "I can buy myself flowers. I can explore a new place today. I can do the research. I can make my cute little websites. I can do all of them! But I can't do them all today.",
    "There's something about rain that is an equalizer, like the night. Trudging through rainwater in one city is pretty close to trudging through rainwater in any other city.",
    "From A: “Is there tension between the side of you that makes up artistic narratives for yourself, and the side of you that strives to see the world as it is and tell the truth?”",
    "Received a letter from A today and I felt my heart burst. I feel so warm but now the pressure to send a letter back soon is even greater. This feels so much better than texting.",
    "Just read an article that said if you have to swallow a frog today, do it first thing. If you have two, swallow the biggest frog first, and I love that phrasing! What is my frog rn?",
    "Funny how with any journaling, I always come out with actionables. Things I can do and if nothing else that is a reason to keep writing. I have so many loves that have been subdued.",
    "I feel very STUCK. I don't know what to do right now and there's no way forward. I'm literally just frozen in time unable to do anything. I wonder why. My body feels physically tired. Is this burnout?",
    "Had a work social which was pretty fun. I wanted to play codenames but we played drawing games instead. I always think they won't be fun but then I get really into them and competitive.",
    "It's raining and I'm sitting on a tram and getting a peak into everyone's gardens as I pass by. I imagine these are the perfect balance of privacy and connection that Alexander mentions.",
    "The word budget comes up a lot when it comes to time -- I have no sense of budget like I now do with money - I have an idea of what I'm willing to spend money on and when I want to save.",
    "One intention that I set for these next few months was to spend less time on food, because as much as I love to cook and plan where I'll have my next meal, it takes so much time and mental space in the day.",
    "Grief always catches up to me in this last week of the year, for the versions of myself that I feel I did not stay true to and for the love I've let dwindle. And yet there is still so much joy.",
    "Just found out that both ice cream places have new flavors every month. I guess this means I get two ice creams a month because it's way too awkward to try the new flavors and not get anything.",
    "It rained today. As in looked like enough rain to warrant an umbrella, yet when I opened mine the drops made no sound. It felt a bit silly to carry an umbrella for raindrops that leave no mark.",
    "One of my mugs is missing. Or maybe it exploded in the kiln. That's a mystery that will never have an ending, and maybe I should make more mugs. Maybe I should learn to not treat these too preciously.",
    "There are a few things I do daily now. I paint a small square of the sky each day. I read a poem each day. It feels impure when I put them on the todo list, after all, rituals shouldn't need checkboxes, no?",
    "Every time we bring back a dog we think what have gotten ourselves into, how have we committed three weeks to a dog that seems so distant from us and has already peed inside. I know I will love her so much.",
    "The past month has been a blur and I don't think I've ever felt this pressed from all sides :((  It was multiple projects in the pursuit of art that all felt very rewarding and maybe not worth the toll it took on my body.",
    "I feel my attention being scrambled all the time. How did I get myself into three hobby classes and all of these projects and work and needing to find friends and the weight of maintaining and maintaining and maintaining.",
    "One thing I want after coming out of this month is away messages for text. To every person who messaged me I wish that I had a banner saying Alicia is not responding to messages this month but still loves you very much <3",
    "In this discomfort I realize that I have a sense of home, small as it is. When the grayness-but-really-white-lack-of-shadows gets to me I wish to be in my room, where the warm glow of half a dozen bulbs and my craft table feel like a hug <3",
    "What would it be like to nurture a project over time without deadline, without decay in excitement that leads to dread? To work on my own secret thing away from external pressures? To come home to it everyday knowing I'd never have to rush.",
    "While the cheesecakes were baking N convinced me to start a new book and I did a warm eye compress. At some point when I was cleaning up my roommate walked in and asked if I was okay, it seemed like I had been in the kitchen for six hours. Just another casual thursday night.",
    "I want to read books again. I want to paint pottery. I want to be well rested. I want to be organized. I want to feel spacious. I want to cuddle. I want to feel the joy I did last summer walking down Prospect st. and passing by the sunflowers with my cheese from whole foods.",
    "Summer in boston is magical. I've never seen much SO GREEN and the water so sparkly and I wouldn't be surprised if there were fairies all around us. I've been a bit in my own head this past week and forgotten to notice how the city was glowing around me. I forgot to breathe.",
    "I'm feeling incredibly vulnerable right now. I don't seem to be doing well at anything I have going on and nothing is a success. I feel like I have a million things to do and I skip half of them each day, so I'm not even doing that much at the end of the day, but I'm still missing everything and having trouble staying afloat.",
    "We skipped a whole summer here. I walked back the way from work - about an hour but more because I think I took a longer way. I decided to walk because I don't like the way the trains feel except for when they're completely empty but G called and I felt so bothered that I decided to walk it off and ended up crying it out too.",
    "N did my tarot reading while I cooked and said I had no cups - I'm not driven by emotions right now. I should take a break or risk burnout, there is an abundance of creativity right now, I shouldn't stay in a job I dislike, and there will soon be a work/relationship situation where I'll have to stand my ground with my values.",
    "The second tarot reading I had stressed the importance of story - the story I tell/about myself as I navigate a new community and choose what to keep and what to leave behind from my previous context. I'm coming into that prophecy now --- every person I meet gets a different story about myself to but they all feel incomplete.",
    "If it's 4 pm and I woke up at noon then it's really like 1pm for a normal person.",
    "I think I left the oven on."
  ];




// // Sort the array by length, with the shortest entries first
// const sortedByLength = entry.sort((a, b) => a.length - b.length);

// // Write the sorted array to a new file
// const fs = require('fs');
// fs.writeFileSync('diarySortedByLength.js', JSON.stringify(sortedByLength, null, 2));